---
title: "Project plan"
author: Witek ten Hove
date: 10-07-2022
format: html
editor: visual
bibliography: bibliography.bib
---

## Overall goal

Today annual Healthcare expenses in the Netherlands amount to 13% of GNP and are exceeding the budgets for Education, Defense and Justice [@ministerie_van_volksgezondheid_verregaande_2022] added together. According to current figures one in seven persons employed works in the Healthcare sector. Projections are that without any change in policies this proportion could reach one in three over the next 40 years.

One of the factors causing the expanding costs of Healthcare is the comparatively low productivity of the sector. Healthcare is typically labor intensive and human interaction is an essential element of service quality. Until now the complexity of tasks limited possibilities for automation. However, with the recent wave of technological innovation new opportunities are arising, especially in the category of facilitating technologies [@visser_kiezen_2021].

![Two categories of healthcare technologies [@visser_kiezen_2021]](images/healthtech.png)

The overall goal of this research project is to add to the development of technological solutions for improving Healthcare efficiency and quality using Operations Research methodologies.

## Targets

-   4 scientific papers:

    -   Outpatient appointment scheduling algorithm

    -   Capacity planning modeling for home care services

    -   Paper 3

    -   Paper 4

-   Attend at least 4 conferences

-   Review at least 4 papers

-   Develop teaching material

## Budget and financing

-   Total budgeted time: 0.6 FTE

-   Financing:

    -   0.2 FTE -\> HAN Bedrijfskunde

    -   0.2 FTE -\> HAN Lectoraat Logistiek en Allianties

    -   0.2 FTE -\> Personal investment

## Planning

```{mermaid}

gantt
    dateFormat  YYYY-MM
    title       Timeline
    axisFormat  %b %y

    section Papers
    Outpatient Appointment Scheduling (OAS):active, pap1, 2022-09, 2023-09
    Home Care Planning (HCP)               :active, pap2, 2022-09, 2023-05
    Paper 3                                :        pap3, 2023-09, 2025-04
    Paper 4                                :        pap4, 2025-04, 2026-12
    
    
    section Learning and<br>development
    Probability/Markov Chains              :active, lnd1, 2022-09, 2022-12
    Simulation techniques                  :        lnd2, after lnd1, 90d
    Conference 1                    :        lnd3, 2023-01, 4d
    Conference 2                    :        lnd4, 2024-01, 4d
    Conference 3                    :        lnd5, 2025-01, 4d
    Conference 4                    :        lnd6, 2026-01, 4d
    
    section Other<br>activities
    Onboarding research project                     :active, oth1, 2022-09, 2022-10
    Setup research and development<br>environments  :active, oth2, 2022-09, 2022-10
    Review Tuncalp e.a.                             :active, oth3, 2022-10, 2022-12
    Review 2                                        :        oth4, after oth3, 360d
    Review 3                                        :        oth5, after oth4, 360d
    Review 4                                        :        oth6, after oth5, 360d
    Review 5                                        :        oth7, after oth6, 360d
    Develop teaching material                       :active, oth8, 2022-09, 2026-12

```

## Work packages

::: panel-tabset
## 2022

+---------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------+----------------------+
| Month         | Work packages                                                         | Results                                                                 | Time                 |
|               |                                                                       |                                                                         |                      |
|               |                                                                       |                                                                         | allocation           |
+===============+=======================================================================+=========================================================================+======================+
| **September** | General:                                                              | General:                                                                | General / OAS / HCP: |
|               |                                                                       |                                                                         |                      |
|               | -   Onboarding Research project                                       | -   Hora Finita, Training Plan                                          | 60 / 20 /20          |
|               |                                                                       |                                                                         |                      |
|               | -   Setup Research and Dev environments                               | -   Research and dev environments (Overleaf, Zotero, RStudio, etc.)     |                      |
|               |                                                                       |                                                                         |                      |
|               | -   Learn Markov Chains                                               | -   Notes Markov Chains                                                 |                      |
|               |                                                                       |                                                                         |                      |
|               | Outpatient Appointment Scheduling (OAS):                              | OAS:                                                                    |                      |
|               |                                                                       |                                                                         |                      |
|               | -   Literature review                                                 | -   Working paper OAS with literature review                            |                      |
|               |                                                                       |                                                                         |                      |
|               | Home Care Planning (HCP):                                             | HCP:                                                                    |                      |
|               |                                                                       |                                                                         |                      |
|               | -   Assess current status of data analysis and develop plan of action | -   Presentation data analysis                                          |                      |
|               |                                                                       |                                                                         |                      |
|               | -   Discuss results with Carinova                                     |                                                                         |                      |
+---------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------+----------------------+
| **October**   | General:                                                              | General:                                                                | General / OAS / HCP: |
|               |                                                                       |                                                                         |                      |
|               | -   Learn Markov Chains                                               | -   Notes Markov Chains                                                 | 20 / 40 /40          |
|               |                                                                       |                                                                         |                      |
|               | OAS:                                                                  | OAS:                                                                    |                      |
|               |                                                                       |                                                                         |                      |
|               | -   Review methods (e.g. Surrogate Models, Response Survey Models)    | -   Working paper OAS with model description                            |                      |
|               |                                                                       |                                                                         |                      |
|               | HCP:                                                                  | HCP:                                                                    |                      |
|               |                                                                       |                                                                         |                      |
|               | -   Complete data analysis                                            | -   Data analysis results                                               |                      |
|               |                                                                       |                                                                         |                      |
|               | -   Complete introduction section paper                               | -   Working paper OAS with introduction, literature review, methodology |                      |
+---------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------+----------------------+
| **November**  | General:                                                              | General:                                                                | General / OAS / HCP: |
|               |                                                                       |                                                                         |                      |
|               | -   Study activities                                                  | -   Notes Markov Chains                                                 | 20 / 50 /30          |
|               |                                                                       |                                                                         |                      |
|               | OAS:                                                                  | OAS:                                                                    |                      |
|               |                                                                       |                                                                         |                      |
|               | -   Develop and test selected algorithms                              | -   Code                                                                |                      |
|               |                                                                       |                                                                         |                      |
|               | HCP:                                                                  | HCP:                                                                    |                      |
|               |                                                                       |                                                                         |                      |
|               | -   Complete analysis supply side                                     | -   Results analysis supply side                                        |                      |
+---------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------+----------------------+
| **December**  | General:                                                              | General:                                                                | General / OAS / HCP: |
|               |                                                                       |                                                                         |                      |
|               | -   Study activities                                                  | -   Notes Markov Chains                                                 | 20 / 50 /30          |
|               |                                                                       |                                                                         |                      |
|               | OAS:                                                                  | OAS:                                                                    |                      |
|               |                                                                       |                                                                         |                      |
|               | -   Develop and test selected algorithms                              | -   Code                                                                |                      |
|               |                                                                       |                                                                         |                      |
|               | HCP:                                                                  | HCP:                                                                    |                      |
|               |                                                                       |                                                                         |                      |
|               | -   Complete paper                                                    | -   Submitted paper                                                     |                      |
|               |                                                                       |                                                                         |                      |
|               | -   Submit paper                                                      |                                                                         |                      |
+---------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------+----------------------+

## 2023

+---------------+---------------------------------+---------------------------+----------------------+
| Month         | Work packages                   | Results                   | Time                 |
|               |                                 |                           |                      |
|               |                                 |                           | allocation           |
+===============+=================================+===========================+======================+
| **January**   | General:                        | General:                  | General / OAS / HCP: |
|               |                                 |                           |                      |
|               | -   Develop teaching material   | -   Teaching material     | 20 / 80 /0           |
|               | -   Study activities            | -   Simulation techniques |                      |
|               |                                 |                           |                      |
|               | OAS:                            | OAS:                      |                      |
|               |                                 |                           |                      |
|               | -   Write paper                 | -   Working paper         |                      |
|               |                                 |                           |                      |
|               | HCP:                            | HCP:                      |                      |
|               |                                 |                           |                      |
|               | -   Wait for review             | -   None                  |                      |
+---------------+---------------------------------+---------------------------+----------------------+
| **February**  | General:                        | General:                  | General / OAS / HCP: |
|               |                                 |                           |                      |
|               | -   Develop teaching material   | -   Teaching material     | 20 / 80 /0           |
|               | -   Study activities            | -   Simulation techniques |                      |
|               |                                 |                           |                      |
|               | OAS:                            | OAS:                      |                      |
|               |                                 |                           |                      |
|               | -   Write paper                 | -   Working paper         |                      |
|               |                                 |                           |                      |
|               | HCP:                            | HCP:                      |                      |
|               |                                 |                           |                      |
|               | -   Wait for review             | -   None                  |                      |
+---------------+---------------------------------+---------------------------+----------------------+
| **March**     | General:                        | General:                  | General / OAS / HCP: |
|               |                                 |                           |                      |
|               | -   Develop teaching material   | -   Teaching material     | 20 / 80 /0           |
|               | -   Study activities            | -   Simulation techniques |                      |
|               |                                 |                           |                      |
|               | OAS:                            | OAS:                      |                      |
|               |                                 |                           |                      |
|               | -   Complete paper              | -   Submitted paper       |                      |
|               | -   Submit paper                |                           |                      |
|               |                                 | HCP:                      |                      |
|               | HCP:                            |                           |                      |
|               |                                 | -   None                  |                      |
|               | -   Wait for review             |                           |                      |
+---------------+---------------------------------+---------------------------+----------------------+
| **April**     | General:                        | General:                  | General / OAS / HCP: |
|               |                                 |                           |                      |
|               | -   Develop teaching material   | -   Teaching material     | 20 / 0 /80           |
|               |                                 |                           |                      |
|               | OAS:                            | OAS:                      |                      |
|               |                                 |                           |                      |
|               | -   Wait for review             | -   None                  |                      |
|               |                                 |                           |                      |
|               | HCP:                            | HCP:                      |                      |
|               |                                 |                           |                      |
|               | -   Process feedback            | -   Reviewed paper        |                      |
+---------------+---------------------------------+---------------------------+----------------------+
| **May**       | General:                        | General:                  | General / OAS / HCP: |
|               |                                 |                           |                      |
|               | -   Develop teaching material   | -   Teaching material     | 20 / 0 /80           |
|               |                                 |                           |                      |
|               | OAS:                            | OAS:                      |                      |
|               |                                 |                           |                      |
|               | -   Wait for review             | -   None                  |                      |
|               |                                 |                           |                      |
|               | HCP:                            | HCP:                      |                      |
|               |                                 |                           |                      |
|               | -   Resubmit reviewed paper     | -   Final version paper   |                      |
+---------------+---------------------------------+---------------------------+----------------------+
| **June**      | General:                        | General:                  | General / OAS        |
|               |                                 |                           |                      |
|               | -   Develop teaching material   | -   Teaching material     | 100 / 0              |
|               | -   Explore new research topics | -   Research suggestions  |                      |
|               |                                 |                           |                      |
|               | OAS:                            | OAS:                      |                      |
|               |                                 |                           |                      |
|               | -   Wait for review             | -   None                  |                      |
+---------------+---------------------------------+---------------------------+----------------------+
| **July**      | General:                        | General:                  | General / OAS        |
|               |                                 |                           |                      |
|               | -   Develop teaching material   | -   Teaching material     | 20 / 80              |
|               | -   Explore new research topics | -   Research suggestions  |                      |
|               |                                 |                           |                      |
|               | OAS:                            | OAS:                      |                      |
|               |                                 |                           |                      |
|               | -   Process feedback            | -   Reviewed paper        |                      |
+---------------+---------------------------------+---------------------------+----------------------+
| **August**    | Holiday                         | Holiday                   | Holiday              |
+---------------+---------------------------------+---------------------------+----------------------+
| **September** | General:                        | General:                  | General / OAS        |
|               |                                 |                           |                      |
|               | -   Develop teaching material   | -   Teaching material     | 20 / 80              |
|               | -   Choose new research topic   | -   New research topic    |                      |
|               |                                 |                           |                      |
|               | OAS:                            | OAS:                      |                      |
|               |                                 |                           |                      |
|               | -   Resubmit reviewed paper     | -   Final version paper   |                      |
+---------------+---------------------------------+---------------------------+----------------------+
| **October**   |                                 |                           |                      |
+---------------+---------------------------------+---------------------------+----------------------+
| **November**  |                                 |                           |                      |
+---------------+---------------------------------+---------------------------+----------------------+
| **December**  |                                 |                           |                      |
+---------------+---------------------------------+---------------------------+----------------------+

## 2024

+---------------+-----------------+------------------+---------------+
| Month         | Work packages   | Results          | Time          |
|               |                 |                  |               |
|               |                 |                  | allocation    |
+===============+=================+==================+===============+
| **January**   |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **February**  |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **March**     |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **April**     |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **May**       |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **June**      |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **July**      |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **August**    |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **September** |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **October**   |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **November**  |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **December**  |                 |                  |               |
+---------------+-----------------+------------------+---------------+

## 2025

+---------------+-----------------+------------------+---------------+
| Month         | Work packages   | Results          | Time          |
|               |                 |                  |               |
|               |                 |                  | allocation    |
+===============+=================+==================+===============+
| **January**   |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **February**  |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **March**     |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **April**     |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **May**       |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **June**      |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **July**      |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **August**    |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **September** |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **October**   |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **November**  |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **December**  |                 |                  |               |
+---------------+-----------------+------------------+---------------+

## 2026

+---------------+-----------------+------------------+---------------+
| Month         | Work packages   | Results          | Time          |
|               |                 |                  |               |
|               |                 |                  | allocation    |
+===============+=================+==================+===============+
| **January**   |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **February**  |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **March**     |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **April**     |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **May**       |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **June**      |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **July**      |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **August**    |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **September** |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **October**   |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **November**  |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **December**  |                 |                  |               |
+---------------+-----------------+------------------+---------------+

## 2027

+---------------+-----------------+------------------+---------------+
| Month         | Work packages   | Results          | Time          |
|               |                 |                  |               |
|               |                 |                  | allocation    |
+===============+=================+==================+===============+
| **January**   |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **February**  |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **March**     |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **April**     |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **April**     |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **June**      |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **July**      |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **August**    |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **September** |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **October**   |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **November**  |                 |                  |               |
+---------------+-----------------+------------------+---------------+
| **December**  |                 |                  |               |
+---------------+-----------------+------------------+---------------+
:::
