---
format:
   revealjs:
      chalkboard: true
editor: visual
---

##  {background-image="title.png"}

<h1 class="r-fit-text" style="color: white">

PROBABILITY

</h1>

<h3 style="color: white">

Witek ten Hove

</h3>

## Acknowlegments

This content is based on the EDX course <br> [Probability - The Science of Uncertainty and Data](https://learning.edx.org/course/course-v1:MITx+6.431x+2T2022/home) <br> by:

-   Prof. John Tsitsiklis

-   Prof. Patrick Jaillet

-   Prof. Dimitri Bertsekas

and their Team

## Probability

Probability Theory

:   A framework for analyzing phenomena with uncertain outcomes

    -   Rules for concistent reasoning

    -   Used for predictions and decisions

## Role of Probability Theory

::: {style="padding: 10px;"}
<canvas id="probTheory" width="900" height="600" style="border:1px solid #d3d3d3;">

</canvas>
:::

```{=html}
<script>

var c = document.getElementById("probTheory");
var ctx = c.getContext("2d");

// Boxes
ctx.fillStyle = 'skyblue';
ctx.fillRect(40, 40, 300, 150);
ctx.fillRect(560, 40, 300, 150);
ctx.fillRect(300, 400, 300, 150);

//Lines
ctx.beginPath();
ctx.moveTo(190,190);
ctx.lineTo(400,400);
ctx.stroke();
ctx.beginPath();
ctx.moveTo(500,400);
ctx.lineTo(710,190);
ctx.stroke();
ctx.beginPath();
ctx.moveTo(560,115);
ctx.lineTo(340,115);
ctx.stroke();

// Arrow heads
ctx.beginPath();
ctx.moveTo(400,400);
ctx.lineTo(390,400);
ctx.lineTo(400,390);
ctx.fillStyle = "black";
ctx.fill();
ctx.beginPath();
ctx.moveTo(710,190);
ctx.lineTo(700,190);
ctx.lineTo(710,200);
ctx.fill();
ctx.beginPath();
ctx.moveTo(340,115);
ctx.lineTo(352,108);
ctx.lineTo(352,122);
ctx.fill();

// Texts
ctx.font = "36px Arial";
ctx.fillText("Real World", 100, 125);
ctx.fillText("Probability", 620, 105);
ctx.fillText("Theory", 620, 145);
ctx.fillText("Inference /", 360, 465);
ctx.fillText("Statistics", 360, 505);
ctx.fillText("Data", 180, 300);
ctx.fillText("Models", 660, 300);
ctx.fillText("Predictions", 370, 100);
ctx.fillText("Decisions", 370, 150);
</script>
```
## Ingredients Probability Calculation

-   Sample space

-   Probability law

-   Event

## Sample Space

-   List [(set)]{style="color:tomato"} of all possible outcomes, [$\Omega$]{style="color:tomato"}
-   The elements of the sample space are [MECE]{style="color:tomato"}

::: {style="padding: 35px;"}
<canvas id="sampleSpace" width="700" height="350" style="border:1px solid #d3d3d3;">

</canvas>
:::

```{=html}
<script>
function randomPoints(canvas, count, color){
  for (var i = 0; i < count; i++) {
    var x = Math.floor(Math.random() * 780);
    var y = Math.floor(Math.random() * 340);
    canvas.fillStyle = color;
    canvas.fillRect(x+10,y,10,10);
  }
}
var c = document.getElementById("sampleSpace");
var ctx = c.getContext("2d");
randomPoints(ctx, 120, 'royalblue');

ctx.font = "80px Arial";
ctx.fillStyle = "black";
ctx.fillText("\u03A9", 10, 80);
</script>
```
## Probablity Law

> Description of beliefs about likelihood of different possible outcomes

## Event

-   A subset of the sample space

-   Probability is assigned to events

::: {style="padding: 35px;"}
<canvas id="eventSet" width="700" height="350" style="border:1px solid #d3d3d3;">

</canvas>
:::

```{=html}
<script>
function randomPoints(canvas, count, color){
  for (var i = 0; i < count; i++) {
    var x = Math.floor(Math.random() * 780);
    var y = Math.floor(Math.random() * 340);
    canvas.fillStyle = color;
    canvas.fillRect(x+10,y,10,10);
  }
}
var c = document.getElementById("eventSet");
var ctx = c.getContext("2d");
randomPoints(ctx, 120, 'royalblue');

ctx.font = "80px Arial";
ctx.fillStyle = "black";
ctx.fillText("\u03A9", 10, 80);

ctx.beginPath();
ctx.arc(150, 240, 80, 0, 2 * Math.PI);
ctx.lineWidth=5
ctx.strokeStyle = "tomato";
ctx.stroke();

ctx.font = "30px Arial";
ctx.fillStyle = "black";
ctx.fillText("Event A", 110, 250);
</script>
```
## Probability Axioms {.smaller}

::: columns
::: {.column width="50%"}
-   $P(A) \geq0$

-   $P(\Omega) = 1$

-   $If \ A \cap B = \emptyset$ <br> $\Rightarrow P(A \cup B) = P(A) + P(B)$
:::

::: {.column width="50%"}
::: {style="padding: 35px;"}
<canvas id="probAxioms" width="700" height="350" style="border:1px solid #d3d3d3;">

</canvas>
:::

```{=html}
<script>
function randomPoints(canvas, count, color){
  for (var i = 0; i < count; i++) {
    var x = Math.floor(Math.random() * 780);
    var y = Math.floor(Math.random() * 340);
    canvas.fillStyle = color;
    canvas.fillRect(x+10,y,10,10);
  }
}
var c = document.getElementById("probAxioms");
var ctx = c.getContext("2d");
randomPoints(ctx, 120, 'royalblue');

ctx.font = "80px Arial";
ctx.fillStyle = "black";
ctx.fillText("\u03A9", 10, 80);

ctx.beginPath();
ctx.arc(150, 240, 80, 0, 2 * Math.PI);
ctx.lineWidth=5
ctx.strokeStyle = "tomato";
ctx.stroke();

ctx.font = "50px Arial";
ctx.fillStyle = "black";
ctx.fillText("A", 130, 250);

ctx.beginPath();
ctx.arc(550, 140, 80, 0, 2 * Math.PI);
ctx.lineWidth=5
ctx.strokeStyle = "tomato";
ctx.stroke();

ctx.font = "50px Arial";
ctx.fillStyle = "black";
ctx.fillText("B", 520, 150);
</script>
```
:::
:::

## Complement of Set

::: columns
::: {.column width="40%"}
$$
A \cup A^C = \Omega
$$

<br>

$$
A \cap A^C = \emptyset
$$
:::

::: {.column width="60%"}
::: {style="padding: 35px;"}
<canvas id="complSet" width="600" height="500" style="border:1px solid #d3d3d3;">

</canvas>
:::

```{=html}
<script>

var c = document.getElementById("complSet");
var ctx = c.getContext("2d");

ctx.font = "50px Arial";
ctx.fillStyle = "black";
ctx.fillText("\u03A9", 10, 50);

ctx.beginPath();
ctx.moveTo(0,50);
ctx.lineTo(550,500);
ctx.stroke();

ctx.font = "50px Arial";
ctx.fillStyle = "black";
ctx.fillText("A", 130, 400);

ctx.font = "50px Arial";
ctx.fillStyle = "black";
ctx.fillText("A\u1D9C", 450, 150);
</script>
```
:::
:::

## Disjoint Sets {.smaller}

::: columns
::: {.column width="50%"}
-   Sets $A$ and $B$ are disjoint if <br> $A \cap B = \emptyset$

-   If $A$ and $B$ are **not** disjoint:<br>$$P(A∪B)=P(A)+P(B) - P(A \cap B)
    $$
:::

::: {.column width="50%"}
<canvas id="notDisjSets" width="700" height="500" style="border:1px solid #d3d3d3;">

</canvas>

```{=html}
<script>
var c = document.getElementById("notDisjSets");
var ctx = c.getContext("2d");

ctx.save();

ctx.font = "50px Arial";
ctx.fillStyle = "black";
ctx.fillText("\u03A9", 10, 50);

ctx.globalAlpha = 0.5;
ctx.lineWidth=3;
ctx.scale(0.4, 1);
ctx.beginPath();
ctx.arc(1400, 250, 200, 0, 2 * Math.PI);
ctx.closePath();
ctx.fillStyle = 'skyblue';
ctx.fill();
ctx.stroke();

ctx.restore();
ctx.save();
ctx.globalAlpha = 0.5;
ctx.lineWidth=3;
ctx.scale(1, 0.4);
ctx.beginPath();
ctx.arc(410, 250, 200, 0, 2 * Math.PI);
ctx.closePath();
ctx.fillStyle = 'tomato';
ctx.fill();
ctx.stroke();

ctx.restore();
ctx.font = "40px Arial";
ctx.fillStyle = "black";
ctx.fillText("A", 550, 300);

ctx.restore();
ctx.font = "40px Arial";
ctx.fillStyle = "black";
ctx.fillText("B", 400, 110);

</script>
```
:::
:::

## Continuous Sample Space

::: columns
::: {.column width="60%"}
Example:

-   $(x,y) \ such \ that \ 0 \leq x,y \leq 1$
-   Uniform probability law: [probability = area]{style="color:tomato"}
-   $P(A) = P( \{ (x,y) \ | \ x+y \leq \frac{1}{2} \}) \\ = Area \ blue \ triangle \\ = \frac{1}{2}*l*h = \frac{1}{8}$
:::

::: {.column width="40%"}
::: {style="padding: 35px;"}
<canvas id="contSamSp" width="500" height="500" style="border:1px solid #d3d3d3;">

</canvas>
:::

```{=html}
<script>
var c = document.getElementById("contSamSp");
var ctx = c.getContext("2d");

// Center
ctx.translate(40, 440);
        
// Add some lines
ctx.beginPath();
ctx.moveTo(0,0);
ctx.lineTo(400,0);
ctx.stroke();
ctx.moveTo(0,0);
ctx.lineTo(0,-400);
ctx.stroke();
ctx.moveTo(0,-300);
ctx.lineTo(300,-300);
ctx.stroke();
ctx.moveTo(300,0);
ctx.lineTo(300,-300);
ctx.stroke();
ctx.moveTo(152,0);
ctx.lineTo(0,-152);
ctx.stroke();
ctx.beginPath();
ctx.moveTo(149,-1);
ctx.lineTo(1,-149);
ctx.lineTo(1,-1);
ctx.fillStyle = "skyblue";
ctx.fill();

// Arrow heads
ctx.beginPath();
ctx.moveTo(0,-400);
ctx.lineTo(5,-395);
ctx.lineTo(-5,-395);
ctx.fillStyle = "black";
ctx.fill();
ctx.beginPath();
ctx.moveTo(400,0);
ctx.lineTo(395,-5);
ctx.lineTo(395, 5);
ctx.fillStyle = "black";
ctx.fill();

ctx.font = "20px Arial";
ctx.fillStyle = "black";
ctx.fillText("0",-20, 20);
ctx.fillText("x",380, 20);
ctx.fillText("y",-20, -380);
ctx.fillText("1",295, 20);
ctx.fillText("1",-20, -295);
ctx.fillText("x+y = 1/2",80, -80);
ctx.font = "40px Arial";
ctx.fillText("A",30, -30);

</script>
```
:::
:::

## Steps Probability Calculation

1.  Specify sample space
2.  Specify probability law
3.  Identify event of interest
4.  Calculate probability of event

## Conditional Probabilities {.smaller}

::: columns
::: {.column width="50%"}
::: {style="padding: 10px;"}
Assume 12 equally likely outcomes <br> $P(A) = \frac{5}{12}, P(B) = \frac{6}{12}$

<canvas id="condProbsA" width="500" height="500" style="border:1px solid #d3d3d3;">

</canvas>
:::

```{=html}
<script>
var c = document.getElementById("condProbsA");
var ctx = c.getContext("2d");

ctx.font = "80px Arial";
ctx.fillStyle = "black";
ctx.fillText("\u03A9", 10, 80);

ctx.lineWidth=3;
ctx.scale(0.7, 1);
ctx.beginPath();
ctx.arc(300, 280, 200, 0, 2 * Math.PI);
ctx.closePath();
ctx.fillStyle = 'skyblue';
ctx.fill();
ctx.stroke();
ctx.restore();

ctx.scale(1, 1);
ctx.globalAlpha = 0.2;
ctx.fillStyle = 'red';
ctx.fillRect(300, 250, 400, 250);
ctx.restore();

ctx.lineWidth=3;
ctx.strokeStyle="black";
ctx.strokeRect(300, 250, 400, 250);

ctx.fillStyle = "black";
ctx.globalAlpha = 1;
ctx.fillText("A", 300, 200);
ctx.fillText("B", 600, 340);

function specificPoints(canvas, count, color, coord) {
  for (var i = 0; i < count; i++) {
    var x = coord[0];
    var y = coord[1];
    canvas.fillStyle = color;
    canvas.fillRect(x+10,y,20,14);
  }
}

const coordsA = [[520, 100], [550, 180], [600, 60], [180, 200], [220, 300], [200, 400], [320, 300], [350, 400]];

for (const coord of coordsA) {
  specificPoints(ctx, coordsA.length, 'red', coord)
}

const coordsB = [[540, 300], [520, 400], [530, 450], [580, 400]];

for (const coord of coordsB) {
  specificPoints(ctx, coordsB.length, 'red', coord)
}

</script>
```
:::

::: {.column width="50%"}
::: {style="padding: 10px;"}
If told [B]{style="color: red"} occured <br> $P(A|B) = \frac{2}{6} = \frac{1}{3}, P(B|B) = 1$

<canvas id="condProbsB" width="500" height="500" style="border:1px solid #d3d3d3;">

</canvas>
:::

```{=html}
<script>
var c2 = document.getElementById("condProbsB");
var ctx2 = c2.getContext("2d");

ctx2.font = "80px Arial";
ctx2.fillStyle = "black";
ctx2.fillText("\u03A9", 10, 80);

ctx2.lineWidth=3;
ctx2.scale(0.7, 1);
ctx2.beginPath();
ctx2.arc(300, 280, 200, 0, 2 * Math.PI);
ctx2.closePath();
ctx2.fillStyle = 'skyblue';
ctx2.fill();
ctx2.stroke();
ctx2.restore();

ctx2.scale(1, 1);
ctx2.globalAlpha = 0.2;
ctx2.fillStyle = 'red';
ctx2.fillRect(300, 250, 400, 250);
ctx2.restore();

ctx2.lineWidth=3;
ctx2.strokeStyle="black";
ctx2.strokeRect(300, 250, 400, 250);

ctx2.fillStyle = "black";
ctx2.globalAlpha = 1;
ctx2.fillText("A", 300, 200);
ctx2.fillText("B", 600, 340);

function specificPoints(canvas, count, color, coord) {
  for (var i = 0; i < count; i++) {
    var x = coord[0];
    var y = coord[1];
    canvas.fillStyle = color;
    canvas.fillRect(x+10,y,20,14);
  }
}

const coordsC = [[320, 300], [350, 400]];

for (const coord of coordsC) {
  specificPoints(ctx2, coordsC.length, 'red', coord)
}

const coordsD = [[540, 300], [520, 400], [530, 450], [580, 400]];

for (const coord of coordsD) {
  specificPoints(ctx2, coordsD.length, 'red', coord)
}

</script>
```
:::
:::

## Definition of Conditional Probability

::: columns
::: {.column width="50%"}
$P(A|B) = \frac{P(A \cap B)}{P(B)}\\Defined\ only\ if\  P(B) > 0$
:::

::: {.column width="50%"}
$P(A \cap B) = \frac{2}{12}, P(B) = \frac{6}{12}$

::: {style="padding: 35px;"}

<canvas id="condProbC" width="680" height="500" style="border:1px solid #d3d3d3;">

</canvas>
:::

```{=html}
<script>
var c = document.getElementById("condProbC");
var ctx = c.getContext("2d");

ctx.font = "80px Arial";
ctx.fillStyle = "black";
ctx.fillText("\u03A9", 10, 80);

ctx.lineWidth=3;
ctx.scale(0.7, 1);
ctx.beginPath();
ctx.arc(300, 280, 200, 0, 2 * Math.PI);
ctx.closePath();
ctx.fillStyle = 'skyblue';
ctx.fill();
ctx.stroke();
ctx.restore();

ctx.scale(1, 1);
ctx.globalAlpha = 0.2;
ctx.fillStyle = 'red';
ctx.fillRect(300, 250, 400, 250);
ctx.restore();

ctx.lineWidth=3;
ctx.strokeStyle="black";
ctx.strokeRect(300, 250, 400, 250);

ctx.fillStyle = "black";
ctx.globalAlpha = 1;
ctx.fillText("A", 300, 200);
ctx.fillText("B", 600, 340);

</script>
```
:::
:::
